version: '2'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - /media/thomas/HDData/postgres_superset:/var/lib/postgresql/data
  superset:
    build: .
    image: amancevice/superset
    restart: always
    depends_on:
      - postgresql
      - mysql
      - redis
    environment:
      MAPBOX_API_KEY: pk.eyJ1IjoidGJvcXVldCIsImEiOiJjaXhmMWFjbG4wMGxlMnRzMTZ3N20ydnFlIn0.CijrplNnJ9AXYFqqx8JMtg
    ports:
      - "8088:8088"
    volumes:
      - "./superset_config.py:/home/superset/superset_config.py"
volumes:
  mysql:
    external: false
  redis:
    external: false
